"""Repository protocols: the only persistence boundary the application layer depends on.

Concrete implementations (SQLite today) live in `personal_graph_os.infrastructure` and are
resolved once at the composition boundary. Services depend only on these protocols.
"""

from __future__ import annotations

from datetime import datetime
from typing import Protocol

from personal_graph_os.domain.activity import ActivityEvent, DiscoveryRun, IdempotencyReceipt
from personal_graph_os.domain.agents import Agent, AgentRun, AgentRunStatus
from personal_graph_os.domain.canvas import Canvas, CanvasPlacement
from personal_graph_os.domain.channel_sync import ChannelSyncState
from personal_graph_os.domain.documents import (
    Collection,
    Document,
    DocumentLink,
    DocumentLinkTargetType,
    DocumentVersion,
    Tag,
)
from personal_graph_os.domain.enrichment import (
    RelationProposal,
    RelationProposalStatus,
    ResourceEnrichmentProfile,
    ResourceEnrichmentProfileVersion,
)
from personal_graph_os.domain.files import Attachment, FileReference
from personal_graph_os.domain.graph import Edge, Node
from personal_graph_os.domain.identifiers import (
    ActivityEventId,
    AgentId,
    AgentRunId,
    AttachmentId,
    CanvasId,
    CanvasPlacementId,
    CollectionId,
    ContextPackId,
    DiscoveryRunId,
    DocumentId,
    DocumentLinkId,
    DocumentVersionId,
    EdgeId,
    FileReferenceId,
    IngestionJobId,
    NodeId,
    RelationProposalId,
    ResourceEnrichmentProfileId,
    ResourceEnrichmentProfileVersionId,
    ResourceId,
    SavedViewId,
    TagId,
    WorkItemChecklistItemId,
    WorkItemId,
    WorkspaceId,
)
from personal_graph_os.domain.ingestion import IngestionJob
from personal_graph_os.domain.research_settings import WorkspaceResearchSettings
from personal_graph_os.domain.resource import (
    RepositoryLabel,
    Resource,
    ResourceKind,
    ResourceLifecycleStatus,
)
from personal_graph_os.domain.resource_content import ResourceContent
from personal_graph_os.domain.schema import Workspace
from personal_graph_os.domain.search import SearchEntityType, SearchHit, SearchScope
from personal_graph_os.domain.views import ContextPack, SavedView
from personal_graph_os.domain.work_items import WorkItem, WorkItemChecklistItem
from personal_graph_os.domain.work_planning import WorkPlanningReceipt


class WorkspaceRepository(Protocol):
    def get(self, workspace_id: WorkspaceId) -> Workspace | None: ...
    def save(self, workspace: Workspace) -> None: ...
    def save_without_commit(self, workspace: Workspace) -> None: ...
    def list_all(self) -> tuple[Workspace, ...]: ...


class NodeRepository(Protocol):
    def get(self, node_id: NodeId) -> Node | None: ...
    def save(self, node: Node) -> None: ...
    def save_without_commit(self, node: Node) -> None: ...
    def list_by_workspace(
        self, workspace_id: WorkspaceId, *, include_archived: bool = False
    ) -> tuple[Node, ...]: ...
    def delete(self, node_id: NodeId) -> None: ...
    def delete_without_commit(self, node_id: NodeId) -> None: ...


class EdgeRepository(Protocol):
    def get(self, edge_id: EdgeId) -> Edge | None: ...
    def save(self, edge: Edge) -> None: ...
    def save_without_commit(self, edge: Edge) -> None: ...
    def save_if_absent_without_commit(self, edge: Edge) -> bool:
        """Insert `edge` atomically only if no edge with the same `(workspace_id, edge_type_id,
        source_node_id, target_node_id)` already exists (review finding S4-R05). Returns whether
        a new row was actually inserted -- enforced by a database uniqueness constraint, not a
        non-atomic read-then-insert, so it is safe even under a genuine concurrent race."""
        ...

    def list_by_workspace(self, workspace_id: WorkspaceId) -> tuple[Edge, ...]: ...
    def list_incident_to_node(self, node_id: NodeId) -> tuple[Edge, ...]: ...
    def delete(self, edge_id: EdgeId) -> None: ...
    def delete_without_commit(self, edge_id: EdgeId) -> None: ...


class CanvasRepository(Protocol):
    def get(self, canvas_id: CanvasId) -> Canvas | None: ...
    def save(self, canvas: Canvas) -> None: ...
    def save_without_commit(self, canvas: Canvas) -> None: ...
    def list_by_workspace(self, workspace_id: WorkspaceId) -> tuple[Canvas, ...]: ...


class CanvasPlacementRepository(Protocol):
    def get(self, placement_id: CanvasPlacementId) -> CanvasPlacement | None: ...
    def save(self, placement: CanvasPlacement) -> None: ...
    def save_without_commit(self, placement: CanvasPlacement) -> None: ...
    def list_by_canvas(self, canvas_id: CanvasId) -> tuple[CanvasPlacement, ...]: ...
    def delete(self, placement_id: CanvasPlacementId) -> None: ...
    def delete_without_commit(self, placement_id: CanvasPlacementId) -> None: ...


class ResourceRepository(Protocol):
    def get(self, resource_id: ResourceId) -> Resource | None: ...
    def get_by_node(self, node_id: NodeId) -> Resource | None: ...
    def get_by_canonical_identifier(
        self, workspace_id: WorkspaceId, canonical_identifier: str
    ) -> Resource | None: ...
    def save(self, resource: Resource) -> None: ...
    def save_without_commit(self, resource: Resource) -> None: ...
    def list_by_workspace(
        self,
        workspace_id: WorkspaceId,
        *,
        kind: ResourceKind | None = None,
        lifecycle_status: ResourceLifecycleStatus | None = None,
        repository_label: RepositoryLabel | None = None,
        last_activity_since: datetime | None = None,
        last_activity_until: datetime | None = None,
    ) -> tuple[Resource, ...]: ...
    def delete_without_commit(self, resource_id: ResourceId) -> None: ...


class SavedViewRepository(Protocol):
    def get(self, saved_view_id: SavedViewId) -> SavedView | None: ...
    def save(self, saved_view: SavedView) -> None: ...
    def save_without_commit(self, saved_view: SavedView) -> None: ...
    def list_by_workspace(self, workspace_id: WorkspaceId) -> tuple[SavedView, ...]: ...
    def delete(self, saved_view_id: SavedViewId) -> None: ...
    def delete_without_commit(self, saved_view_id: SavedViewId) -> None: ...


class ResourceContentRepository(Protocol):
    """One persisted source-content row per resource (EP-2026-012 ST-13): derived evidence,
    replaced wholesale on refresh, so an upsert is the only write and there is no
    `save_without_commit` — content never joins a multi-table unit-of-work aggregate."""

    def get_by_resource(self, resource_id: ResourceId) -> ResourceContent | None: ...
    def save(self, content: ResourceContent) -> None: ...


class DiscoveryRunRepository(Protocol):
    def get(self, discovery_run_id: DiscoveryRunId) -> DiscoveryRun | None: ...
    def save(self, discovery_run: DiscoveryRun) -> None: ...
    def save_without_commit(self, discovery_run: DiscoveryRun) -> None: ...
    def list_by_workspace(self, workspace_id: WorkspaceId) -> tuple[DiscoveryRun, ...]: ...


class AttachmentRepository(Protocol):
    def get(self, attachment_id: AttachmentId) -> Attachment | None: ...
    def list_by_node(self, node_id: NodeId) -> tuple[Attachment, ...]: ...
    def save(self, attachment: Attachment) -> None: ...
    def save_without_commit(self, attachment: Attachment) -> None: ...
    def delete(self, attachment_id: AttachmentId) -> None: ...
    def delete_without_commit(self, attachment_id: AttachmentId) -> None: ...


class FileReferenceRepository(Protocol):
    def get(self, file_reference_id: FileReferenceId) -> FileReference | None: ...
    def list_by_node(self, node_id: NodeId) -> tuple[FileReference, ...]: ...
    def save(self, file_reference: FileReference) -> None: ...
    def save_without_commit(self, file_reference: FileReference) -> None: ...
    def delete(self, file_reference_id: FileReferenceId) -> None: ...
    def delete_without_commit(self, file_reference_id: FileReferenceId) -> None: ...


class ResearchSettingsRepository(Protocol):
    def get(self, workspace_id: WorkspaceId) -> WorkspaceResearchSettings | None: ...
    def save(self, settings: WorkspaceResearchSettings) -> None: ...
    def save_without_commit(self, settings: WorkspaceResearchSettings) -> None: ...


class ContextPackRepository(Protocol):
    def get(self, context_pack_id: ContextPackId) -> ContextPack | None: ...
    def save(self, context_pack: ContextPack) -> None: ...
    def save_without_commit(self, context_pack: ContextPack) -> None: ...
    def list_by_workspace(self, workspace_id: WorkspaceId) -> tuple[ContextPack, ...]: ...
    def delete(self, context_pack_id: ContextPackId) -> None: ...
    def delete_without_commit(self, context_pack_id: ContextPackId) -> None: ...


class ActivityEventRepository(Protocol):
    def get_by_request(
        self, workspace_id: WorkspaceId, source: str, actor_name: str, request_id: str
    ) -> ActivityEvent | None: ...
    def get(self, event_id: ActivityEventId) -> ActivityEvent | None: ...
    def get_by_reverses(self, reversed_event_id: ActivityEventId) -> ActivityEvent | None: ...
    def list_by_workspace(
        self,
        workspace_id: WorkspaceId,
        *,
        limit: int,
        before_occurred_at: str | None = None,
        before_id: str | None = None,
    ) -> tuple[ActivityEvent, ...]: ...
    def list_by_entity(
        self,
        entity_type: str,
        entity_id: str,
        *,
        limit: int,
        before_occurred_at: str | None = None,
        before_id: str | None = None,
    ) -> tuple[ActivityEvent, ...]: ...
    def save(self, event: ActivityEvent) -> None: ...
    def save_without_commit(self, event: ActivityEvent) -> None: ...


class IdempotencyReceiptRepository(Protocol):
    def get_by_request(
        self, workspace_id: WorkspaceId, source: str, actor_name: str, request_id: str
    ) -> IdempotencyReceipt | None: ...
    def save_without_commit(self, receipt: IdempotencyReceipt) -> None: ...


class CollectionRepository(Protocol):
    def get(self, collection_id: CollectionId) -> Collection | None: ...
    def list_by_workspace(self, workspace_id: WorkspaceId) -> tuple[Collection, ...]: ...
    def save(self, collection: Collection) -> None: ...
    def save_without_commit(self, collection: Collection) -> None: ...


class TagRepository(Protocol):
    def get(self, tag_id: TagId) -> Tag | None: ...
    def get_by_name(self, workspace_id: WorkspaceId, name: str) -> Tag | None: ...
    def list_by_workspace(self, workspace_id: WorkspaceId) -> tuple[Tag, ...]: ...
    def save(self, tag: Tag) -> None: ...
    def save_without_commit(self, tag: Tag) -> None: ...


class DocumentRepository(Protocol):
    def get(self, document_id: DocumentId) -> Document | None: ...
    def list_by_workspace(
        self, workspace_id: WorkspaceId, *, include_archived: bool = False
    ) -> tuple[Document, ...]: ...
    def list_by_collection(self, collection_id: CollectionId) -> tuple[Document, ...]: ...
    def save(self, document: Document) -> None: ...
    def save_without_commit(self, document: Document) -> None: ...
    def delete_without_commit(self, document_id: DocumentId) -> None: ...


class DocumentVersionRepository(Protocol):
    def get(self, document_version_id: DocumentVersionId) -> DocumentVersion | None: ...
    def list_by_document(self, document_id: DocumentId) -> tuple[DocumentVersion, ...]: ...
    def latest_for_document(self, document_id: DocumentId) -> DocumentVersion | None: ...
    def save_without_commit(self, document_version: DocumentVersion) -> None: ...


class DocumentLinkRepository(Protocol):
    def list_by_document(self, document_id: DocumentId) -> tuple[DocumentLink, ...]: ...
    def list_by_target(
        self, target_type: DocumentLinkTargetType, target_id: str
    ) -> tuple[DocumentLink, ...]: ...
    def save(self, document_link: DocumentLink) -> None: ...
    def save_without_commit(self, document_link: DocumentLink) -> None: ...
    def delete(self, document_link_id: DocumentLinkId) -> None: ...
    def delete_without_commit(self, document_link_id: DocumentLinkId) -> None: ...


class IngestionJobRepository(Protocol):
    def get(self, ingestion_job_id: IngestionJobId) -> IngestionJob | None: ...
    def get_by_source(
        self, workspace_id: WorkspaceId, source: str, source_identifier: str
    ) -> IngestionJob | None: ...
    def get_by_result_entity(
        self, workspace_id: WorkspaceId, *, result_entity_type: str, result_entity_id: str
    ) -> IngestionJob | None:
        """The most recent job whose committed write produced `(result_entity_type,
        result_entity_id)` (EP-2026-012 ST-06's Research/Repository job-provenance requirement;
        review finding S6-R02: more than one job can legitimately resolve to the same result over
        time, so this deterministically returns the latest, not an arbitrary match) -- `None`
        when no job recorded that result (e.g. a resource created outside Capture)."""
        ...

    def list_by_workspace(self, workspace_id: WorkspaceId) -> tuple[IngestionJob, ...]: ...
    def save(self, ingestion_job: IngestionJob) -> None: ...
    def save_without_commit(self, ingestion_job: IngestionJob) -> None: ...


class ChannelSyncStateRepository(Protocol):
    """Per-channel ingress cursor, one row per `(workspace_id, channel)` (EP-2026-012 ST-10/11).

    The upsert is the production write contract (`ClickupService`/`TelegramService` advance the
    cursor only after a successful import, monotonic `MAX` -- S10-F02). `get` is the resume read:
    `TelegramPoller` starts each poll at `int(cursor) + 1` (ST-11), so a restart continues from
    the last confirmed update instead of re-reading the whole backlog.
    """

    def get(self, workspace_id: WorkspaceId, channel: str) -> ChannelSyncState | None: ...
    def save_without_commit(self, state: ChannelSyncState) -> None: ...


class WorkItemRepository(Protocol):
    def get(self, work_item_id: WorkItemId) -> WorkItem | None: ...
    def get_by_node(self, node_id: NodeId) -> WorkItem | None: ...
    def list_by_workspace(self, workspace_id: WorkspaceId) -> tuple[WorkItem, ...]: ...
    def list_by_parent(self, parent_id: WorkItemId) -> tuple[WorkItem, ...]: ...
    def save(self, work_item: WorkItem) -> None: ...
    def save_without_commit(self, work_item: WorkItem) -> None: ...
    def delete_without_commit(self, work_item_id: WorkItemId) -> None: ...


class WorkItemChecklistItemRepository(Protocol):
    def get(self, item_id: WorkItemChecklistItemId) -> WorkItemChecklistItem | None: ...
    def list_by_work_item(self, work_item_id: WorkItemId) -> tuple[WorkItemChecklistItem, ...]: ...
    def save(self, item: WorkItemChecklistItem) -> None: ...
    def save_without_commit(self, item: WorkItemChecklistItem) -> None: ...
    def delete(self, item_id: WorkItemChecklistItemId) -> None: ...
    def delete_without_commit(self, item_id: WorkItemChecklistItemId) -> None: ...


class ResourceEnrichmentProfileRepository(Protocol):
    def get(self, profile_id: ResourceEnrichmentProfileId) -> ResourceEnrichmentProfile | None: ...
    def get_by_identifier(
        self, workspace_id: WorkspaceId, canonical_identifier: str
    ) -> ResourceEnrichmentProfile | None: ...
    def save_without_commit(self, profile: ResourceEnrichmentProfile) -> None: ...


class ResourceEnrichmentProfileVersionRepository(Protocol):
    def get(
        self, version_id: ResourceEnrichmentProfileVersionId
    ) -> ResourceEnrichmentProfileVersion | None: ...
    def list_by_profile(
        self, profile_id: ResourceEnrichmentProfileId
    ) -> tuple[ResourceEnrichmentProfileVersion, ...]: ...

    def create_version_without_commit(
        self, version: ResourceEnrichmentProfileVersion, *, expected_current_version_number: int
    ) -> None:
        """Insert `version`, guarded by expected-version optimistic concurrency.

        Raises `personal_graph_os.domain.enrichment.ConcurrentEnrichmentUpdateError` if the
        profile's actual current version number no longer matches
        `expected_current_version_number` -- another write already landed, so this caller must
        re-read and retry rather than silently overwrite it.
        """
        ...


class RelationProposalRepository(Protocol):
    def get(self, proposal_id: RelationProposalId) -> RelationProposal | None: ...
    def list_by_workspace(
        self, workspace_id: WorkspaceId, *, status: RelationProposalStatus | None = None
    ) -> tuple[RelationProposal, ...]: ...
    def save_without_commit(self, proposal: RelationProposal) -> None: ...


class WorkPlanningReceiptRepository(Protocol):
    def get_by_ingestion_job(
        self, ingestion_job_id: IngestionJobId
    ) -> WorkPlanningReceipt | None: ...
    def save_without_commit(self, receipt: WorkPlanningReceipt) -> None: ...


class SearchIndexRepository(Protocol):
    def index_document(
        self,
        *,
        workspace_id: WorkspaceId,
        entity_type: SearchEntityType,
        entity_id: str,
        text: str,
        scope: SearchScope = SearchScope.GRAPH,
    ) -> None: ...
    def remove_document(self, *, entity_type: SearchEntityType, entity_id: str) -> None: ...
    def search(
        self, workspace_id: WorkspaceId, query_text: str, *, limit: int = 50
    ) -> tuple[SearchHit, ...]: ...


class AgentRepository(Protocol):
    def list_agents(self) -> tuple[Agent, ...]: ...
    def get(self, agent_id: AgentId) -> Agent | None: ...
    def save_without_commit(self, agent: Agent) -> None: ...
    def delete_without_commit(self, agent_id: AgentId) -> None: ...
    def record_run_without_commit(self, run: AgentRun) -> None: ...
    def update_run_status_without_commit(
        self, run_id: AgentRunId, status: AgentRunStatus | str
    ) -> AgentRun | None: ...
    def list_runs_for_agent(
        self, agent_id: AgentId, *, limit: int = 50
    ) -> tuple[AgentRun, ...]: ...
    def list_recent_runs(self, *, limit: int = 50) -> tuple[AgentRun, ...]: ...
    def get_run(self, run_id: AgentRunId) -> AgentRun | None: ...
