"""Repository protocols: the only persistence boundary the application layer depends on.

Concrete implementations (SQLite today) live in `personal_graph_os.infrastructure` and are
resolved once at the composition boundary. Services depend only on these protocols.
"""

from __future__ import annotations

from typing import Protocol

from personal_graph_os.domain.activity import DiscoveryRun
from personal_graph_os.domain.canvas import Canvas, CanvasPlacement
from personal_graph_os.domain.graph import Edge, Node
from personal_graph_os.domain.identifiers import (
    CanvasId,
    CanvasPlacementId,
    DiscoveryRunId,
    EdgeId,
    NodeId,
    ResourceId,
    SavedViewId,
    WorkspaceId,
)
from personal_graph_os.domain.research_settings import WorkspaceResearchSettings
from personal_graph_os.domain.resource import Resource
from personal_graph_os.domain.schema import Workspace
from personal_graph_os.domain.search import SearchEntityType, SearchHit
from personal_graph_os.domain.views import SavedView


class WorkspaceRepository(Protocol):
    def get(self, workspace_id: WorkspaceId) -> Workspace | None: ...
    def save(self, workspace: Workspace) -> None: ...
    def list_all(self) -> tuple[Workspace, ...]: ...


class NodeRepository(Protocol):
    def get(self, node_id: NodeId) -> Node | None: ...
    def save(self, node: Node) -> None: ...
    def save_without_commit(self, node: Node) -> None: ...
    def list_by_workspace(
        self, workspace_id: WorkspaceId, *, include_archived: bool = False
    ) -> tuple[Node, ...]: ...
    def delete(self, node_id: NodeId) -> None: ...


class EdgeRepository(Protocol):
    def get(self, edge_id: EdgeId) -> Edge | None: ...
    def save(self, edge: Edge) -> None: ...
    def list_by_workspace(self, workspace_id: WorkspaceId) -> tuple[Edge, ...]: ...
    def list_incident_to_node(self, node_id: NodeId) -> tuple[Edge, ...]: ...
    def delete(self, edge_id: EdgeId) -> None: ...


class CanvasRepository(Protocol):
    def get(self, canvas_id: CanvasId) -> Canvas | None: ...
    def save(self, canvas: Canvas) -> None: ...
    def list_by_workspace(self, workspace_id: WorkspaceId) -> tuple[Canvas, ...]: ...


class CanvasPlacementRepository(Protocol):
    def get(self, placement_id: CanvasPlacementId) -> CanvasPlacement | None: ...
    def save(self, placement: CanvasPlacement) -> None: ...
    def list_by_canvas(self, canvas_id: CanvasId) -> tuple[CanvasPlacement, ...]: ...
    def delete(self, placement_id: CanvasPlacementId) -> None: ...


class ResourceRepository(Protocol):
    def get(self, resource_id: ResourceId) -> Resource | None: ...
    def get_by_node(self, node_id: NodeId) -> Resource | None: ...
    def get_by_canonical_identifier(
        self, workspace_id: WorkspaceId, canonical_identifier: str
    ) -> Resource | None: ...
    def save(self, resource: Resource) -> None: ...
    def save_without_commit(self, resource: Resource) -> None: ...
    def list_by_workspace(self, workspace_id: WorkspaceId) -> tuple[Resource, ...]: ...


class SavedViewRepository(Protocol):
    def get(self, saved_view_id: SavedViewId) -> SavedView | None: ...
    def save(self, saved_view: SavedView) -> None: ...
    def list_by_workspace(self, workspace_id: WorkspaceId) -> tuple[SavedView, ...]: ...
    def delete(self, saved_view_id: SavedViewId) -> None: ...


class DiscoveryRunRepository(Protocol):
    def get(self, discovery_run_id: DiscoveryRunId) -> DiscoveryRun | None: ...
    def save(self, discovery_run: DiscoveryRun) -> None: ...
    def save_without_commit(self, discovery_run: DiscoveryRun) -> None: ...
    def list_by_workspace(self, workspace_id: WorkspaceId) -> tuple[DiscoveryRun, ...]: ...


class ResearchSettingsRepository(Protocol):
    def get(self, workspace_id: WorkspaceId) -> WorkspaceResearchSettings | None: ...
    def save(self, settings: WorkspaceResearchSettings) -> None: ...


class SearchIndexRepository(Protocol):
    def index_document(
        self,
        *,
        workspace_id: WorkspaceId,
        entity_type: SearchEntityType,
        entity_id: str,
        text: str,
    ) -> None: ...
    def remove_document(self, *, entity_type: SearchEntityType, entity_id: str) -> None: ...
    def search(
        self, workspace_id: WorkspaceId, query_text: str, *, limit: int = 50
    ) -> tuple[SearchHit, ...]: ...
